// Code generated by logcopter-gen; DO NOT EDIT.

package refactorindex

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.refactorio.pkg.refactorindex")
