- type: local
  path: /home/manuel/Downloads/gopls_deep_dive_analysis.md
  lastFetched: 2026-02-03T18:24:34.78690456-05:00
- type: local
  path: /home/manuel/Downloads/gopls CLI Complete Guide.md
  lastFetched: 2026-02-03T18:24:37.702314558-05:00
